### ISSUE TITLE
Green user having brew build trouble, possibly libsonic related?

### ISSUE THREAD

**Issue by fingerfunk** [anarchivist/homebrew-espeak-ng#2]
Hello,
I'm a green music-type at a beginner level of skill in the terminal homebrew world. I'm getting errors when attempting to install ESPEAK-NG and MBROLA. I've gotten through most of the dependencies on the main site. 
Brew Doctor says I'm clean but am getting build errors on a Catalina 10.15.5 Macbook Air w/ Python 2.7.16 It seems my errors are possibly "lisonic" related(?) or perhaps Espeak-NG will not work on my intel mac air?

Thanks for any help you can provide! I use these old computerized voice synths in some of my music/art. :)

    ESPEAK-NG INSTALL:
MacBook-Air:~ brt$  brew install --HEAD anarchivist/espeak-ng/espeak-ng
==> Installing espeak-ng from anarchivist/espeak-ng
==> Cloning https://github.com/waywardgeek/sonic.git
Updating /Users/brt/Library/Caches/Homebrew/waywardgeek-sonic--git
==> Checking out branch master
Already on 'master'
Your branch is up to date with 'origin/master'.
HEAD is now at ba33141 Merge pull request #23 from danielbair/sonic-mac
==> Cloning https://github.com/espeak-ng/espeak-ng.git
Cloning into '/Users/brt/Library/Caches/Homebrew/espeak-ng--git'...
==> Checking out branch master
Already on 'master'
Your branch is up to date with 'origin/master'.
==> Installing dependencies for anarchivist/espeak-ng/espeak-ng: anarchivist/espeak-ng/waywardgeek-sonic
==> Installing anarchivist/espeak-ng/espeak-ng dependency: anarchivist/espe
Error: An exception occurred within a child process:
  Utils::Inreplace::Error: inreplace failed
Makefile:
  expected replacement of "libsonic.so.$(LIB_TAG)" with "libsonic.$(LIB_TAG).dylib"
  expected replacement of "libsonic.so.0" with "libsonic.0.dylib"

MacBook-Air:~ brt$ 

     MBROLA INSTALL:
MacBook-Air:~ brt$  brew install --HEAD anarchivist/espeak-ng/mbrola
==> Installing mbrola from anarchivist/espeak-ng
==> Cloning https://github.com/numediart/MBROLA.git
Updating /Users/brt/Library/Caches/Homebrew/mbrola--git
==> Checking out branch master
Already on 'master'
Your branch is up to date with 'origin/master'.
HEAD is now at 4d9c85d Makefile compiler adjustments
==> make
Last 15 lines from /Users/brt/Library/Logs/Homebrew/mbrola/01.make:
 ^
1 error generated.
make: *** [Bin/Standalone/Engine/diphone.o] Error 1
make: *** Waiting for unfinished jobs....
1 error generated.
1 error generated.
make: *** [Bin/Standalone/Standalone/synth.o] Error 1
make: *** [Bin/Standalone/Engine/mbrola.o] Error 1
In file included from Parser/phone.c:37:
In file included from Parser/phone.h:32:
Misc/common.h:105:2: error: "Both LITTLE_ENDIAN and BIG_ENDIAN are defined. It should not happen and this probably means your platform is not fully tested and handled."
#error "Both LITTLE_ENDIAN and BIG_ENDIAN are defined. It should not happen and this probably means your platform is not fully tested and handled."
 ^
1 error generated.
make: *** [Bin/Standalone/Parser/phone.o] Error 1

If reporting this issue please do so at (not Homebrew/brew or Homebrew/core):
  https://github.com/anarchivist/homebrew-espeak-ng/issues

Please create pull requests instead of asking for help on Homebrew's GitHub,
Twitter or any other official channels.

**Comment by Git-Christopher** [comment]
closed my previous issue and +1 on the above issue, which is the same as my own. 

hello! attempting to install your formulae via terminal and am greeted with the following error. any help appreciated.

(base) christopher-mauldins-computer:~ Kit$ brew install anarchivist/espeak-ng/mbrola
Error: anarchivist/espeak-ng/mbrola is a head-only formula.
To install it, run:
brew install --HEAD anarchivist/espeak-ng/mbrola
(base) christopher-mauldins-computer:~ Kit$ brew install --HEAD anarchivist/espeak-ng/mbrola
==> Installing mbrola from anarchivist/espeak-ng
==> Cloning https://github.com/numediart/MBROLA.git
Cloning into '/Users/Kit/Library/Caches/Homebrew/mbrola--git'...
==> Checking out branch master
Already on 'master'
Your branch is up to date with 'origin/master'.
Warning: A newer Command Line Tools release is available.
Update them from Software Update in System Preferences or run:
softwareupdate --all --install --force

If that doesn't show you any updates, run:
sudo rm -rf /Library/Developer/CommandLineTools
sudo xcode-select --install

Alternatively, manually download them from:
https://developer.apple.com/download/more/.
You should download the Command Line Tools for Xcode 12.4.

==> make
Last 15 lines from /Users/Kit/Library/Logs/Homebrew/mbrola/01.make:
#error "Both LITTLE_ENDIAN and BIG_ENDIAN are defined. It should not happen and this probably means your platform is not fully tested and handled."
^
In file included from Parser/parser_input.c:28:
In file included from Parser/parser_input.h:31:
In file included from Parser/parser.h:29:
In file included from Parser/phone.h:32:
Misc/common.h:105:2: error: "Both LITTLE_ENDIAN and BIG_ENDIAN are defined. It should not happen and this probably means your platform is not fully tested and handled."
#error "Both LITTLE_ENDIAN and BIG_ENDIAN are defined. It should not happen and this probably means your platform is not fully tested and handled."
^
1 error generated.
1 error generated.
make: *** [Bin/Standalone/Misc/audio.o] Error 1
1 error generated.
make: *** [Bin/Standalone/Parser/parser_input.o] Error 1
make: *** [Bin/Standalone/Parser/phonbuff.o] Error 1

**Comment by anarchivist** [comment]
Hello - please try the `mbrola-fix` branch referenced in #4. You may need to attempt building mbrola using Homebrew's verbose mode (`-v`)
